CREATE DATABASE MEDICAMENTOS_DB;

CREATE TABLE MEDICAMENTO(
ID_MEDICAMENTO INT PRIMARY KEY auto_increment,
NOMBRE_MEDICAMENTO VARCHAR (100) NOT NULL, 
DESCRIPCION TEXT NOT NULL,
INDICACIONES TEXT NOT NULL,
VIA_DE_ADMINISTRACION VARCHAR (45) NOT NULL,
DOSIS VARCHAR (200)
);
CREATE TABLE USUARIO(
ID_USUARIO INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(45) NOT NULL,
APELLIDOS VARCHAR(70) NOT NULL,
EDAD INT(10) NOT NULL,
SEXO VARCHAR (45) NOT NULL,
NOMBRE_DE_USUARIO VARCHAR (45) NOT NULL,
PSWD VARCHAR (45) NOT NULL
);
CREATE TABLE TIPO_USUARIO(
ID_TIPO_USUARIO INT PRIMARY KEY auto_increment, 
DOCTOR VARCHAR (45) NOT NULL,
ADMINISTRATIVO VARCHAR(45) NOT NULL,
ALMACENISTA VARCHAR(45) NOT NULL
);

ALTER TABLE USUARIO
ADD COLUMN ID_TIPO_USUARIO,
ADD CONSTRAINT 'FK_ID_TIPO_USUARIO' FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID_USUARIO);


